version: '3.9'

services:

  builder:
    image: spring-boot-template:builder
    container_name: spring-boot-template-builder
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - build-cache:/root/.gradle/caches/
      - ./build:/app/build

  app:
    image: spring-boot-template:latest
    container_name: spring-boot-template
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4326:4326"

  docker-scan:
    image: aquasec/trivy:latest
    container_name: docker-scan
    volumes:
      - .:/results

volumes:
  build-cache:
    name: build-cache
