apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-template
  name: spring-boot-template
spec:
  ports:
    - name: "4326"
      port: 4326
      targetPort: 4326
  selector:
    app: spring-boot-template
status:
  loadBalancer: {}

