
server:
  port: 4326

info:
  app:
    name: ${project.name}
    version: ${project.version}

# MVC
spring:
  problemdetails:
    enabled: true
  datasource:
    url: jdbc:h2:mem:template
  liquibase:
    change-log: classpath:/db/changelog/master.yml
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
