name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Gradle Build
        run: make build

      - name: OWASP Dependency Check
        run: make owasp-check

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hadolint Dockerfile
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile

      - name: Hadolint build.Dockerfile
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: build.Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: make image-build

      - name: Run Docker image scan
        run: make image-scan DOCKER_SCAN_ARGS="-q -f sarif -o /results/trivy-results.sarif"

      - name: Upload Docker image scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/trivy-results.sarif

  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.13.2'

      - name: Helm Lint
        run: helm lint helm-chart

      - name: Helm template (local)
        run: helm template helm-chart --values local.values.yaml

      - name: Helm template (localstack)
        run: helm template helm-chart --values localstack.values.yaml
